services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: [user_name]
      POSTGRES_PASSWORD: [password]
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - DB_USER= [username]
      - DB_PASSWORD= [password]
      - DB_NAME= [DB_name]
      - DB_HOST= db
      - DB_PORT= 5432
  frontend:
    build: ./frontend-new
    ports:
      - "3000:3000"
    depends_on:
      - backend
